version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres: